#!/usr/bin/env node
// Guards the specification. Zero dependencies, so it runs before `pnpm install`.
//
//   node scripts/guard-spec.mjs                    check everything
//   node scripts/guard-spec.mjs --write            regenerate packages/spec/requirements.json
//   node scripts/guard-spec.mjs --coverage         count requirement ids named by a test
//   node scripts/guard-spec.mjs --coverage --list  ...and list the ids no test names yet
//
// Checks, each reported with a stable slug (AGENTS.md → Decisions 2 and 3):
//   unique-id         every requirement id is defined once
//   one-must          every requirement holds exactly one MUST / MUST NOT, and no SHOULD / MAY
//   known-id          every DSOR-XXX-NN mentioned in any markdown file is defined by the spec
//   link-target       every relative markdown link, and its #anchor, resolves
//   registry-current  packages/spec/requirements.json equals what the spec says today
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, normalize, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SPEC_DIR = join(ROOT, "specs", "dsor");
const REGISTRY = join(ROOT, "packages", "spec", "requirements.json");
const REQUIREMENT = /^- \*\*\[(DSOR-[A-Z]+-\d+[a-z]?) · (L1|L2|L3|RP|STACK)\]\*\* (.*)$/;
const ID = /DSOR-[A-Z]+-\d+[a-z]?/g;
const SKIP = new Set(["node_modules", "dist", ".git"]);

const walk = (dir, keep) =>
  readdirSync(dir).flatMap((name) => {
    if (SKIP.has(name)) return [];
    const p = join(dir, name);
    if (statSync(p).isDirectory()) return walk(p, keep);
    return keep(p) ? [p] : [];
  });

const stripLinks = (s) => s.replace(/\[([^\]]+)\]\([^)]*\)/g, "$1");
const stripCode = (s) => s.replace(/`[^`]*`/g, "");

// GitHub's heading-to-anchor rule, close enough for the headings this repo uses.
const slug = (heading) =>
  heading
    .trim()
    .toLowerCase()
    .replace(/[`*_]/g, "")
    .replace(/[^\p{L}\p{N}_\- ]/gu, "")
    .replace(/ /g, "-");

/** Lines of a markdown file with fenced code blocks blanked out. */
const prose = (text) => {
  let fence = false;
  return text.split("\n").map((line) => {
    if (line.startsWith("```")) {
      fence = !fence;
      return "";
    }
    return fence ? "" : line;
  });
};

function readRequirements() {
  const found = [];
  const files = readdirSync(SPEC_DIR)
    .filter((f) => f.endsWith(".md"))
    .sort();
  for (const file of files) {
    let section = null;
    for (const line of prose(readFileSync(join(SPEC_DIR, file), "utf8"))) {
      const heading = line.match(/^## (\d+(?:\.\d+)?)[. ]/);
      if (heading) section = heading[1];
      const m = line.match(REQUIREMENT);
      if (m) {
        found.push({
          id: m[1],
          level: m[2],
          section,
          text: stripLinks(m[3]),
          file: `specs/dsor/${file}`,
        });
      }
    }
  }
  return found;
}

const failures = new Set();
const fail = (check, detail) => failures.add(`error: ${check} — ${detail}`);

const requirements = readRequirements();
const ids = new Set();
for (const r of requirements) {
  if (ids.has(r.id)) fail("unique-id", `${r.id} is defined twice`);
  ids.add(r.id);
  const bare = stripCode(r.text);
  const musts = (bare.match(/\bMUST\b/g) ?? []).length;
  if (musts !== 1) fail("one-must", `${r.id} has ${musts} MUSTs; one requirement, one MUST`);
  if (/\b(SHOULD|MAY)\b/.test(bare)) fail("one-must", `${r.id} mixes SHOULD or MAY into a MUST`);
}

const markdown = walk(ROOT, (p) => p.endsWith(".md"));
const anchors = new Map();
for (const file of markdown) {
  const set = new Set();
  for (const line of prose(readFileSync(file, "utf8"))) {
    const heading = line.match(/^#{1,6} (.*)$/);
    if (heading) set.add(slug(heading[1]));
  }
  anchors.set(normalize(file), set);
}
for (const file of markdown) {
  const where = relative(ROOT, file);
  for (const line of prose(readFileSync(file, "utf8"))) {
    const bare = stripCode(line);
    for (const id of bare.match(ID) ?? []) {
      if (!ids.has(id)) fail("known-id", `${where} mentions ${id}, which the spec does not define`);
    }
    for (const m of bare.matchAll(/\]\(([^)\s]+)\)/g)) {
      const href = m[1];
      if (/^[a-z]+:/i.test(href)) continue;
      const [path, anchor] = href.split("#");
      const target = normalize(path ? join(dirname(file), path) : file);
      if (!existsSync(target)) {
        fail("link-target", `${where} links to a missing file: ${href}`);
      } else if (anchor && target.endsWith(".md") && !anchors.get(target)?.has(anchor)) {
        fail("link-target", `${where} links to a missing anchor: ${href}`);
      }
    }
  }
}

const rendered =
  JSON.stringify(
    {
      specification: "DSoR",
      version: "1.3.1",
      note: "Generated by `pnpm guard --write` from specs/dsor/*.md. Do not edit by hand.",
      requirements,
    },
    null,
    2,
  ) + "\n";

if (process.argv.includes("--write")) {
  writeFileSync(REGISTRY, rendered);
  console.log(`wrote ${requirements.length} requirements to ${relative(ROOT, REGISTRY)}`);
} else if (!existsSync(REGISTRY) || readFileSync(REGISTRY, "utf8") !== rendered) {
  fail("registry-current", "packages/spec/requirements.json is stale; run: pnpm guard --write");
}

if (process.argv.includes("--coverage")) {
  const tests = walk(join(ROOT, "packages"), (p) => p.endsWith(".test.ts"));
  const named = new Set(tests.flatMap((t) => readFileSync(t, "utf8").match(ID) ?? []));
  for (const level of ["L1", "L2", "L3", "RP", "STACK"]) {
    const all = requirements.filter((r) => r.level === level);
    const open = all.filter((r) => !named.has(r.id));
    const done = String(all.length - open.length).padStart(3);
    console.log(`${level.padEnd(5)} ${done} / ${String(all.length).padStart(3)} named by a test`);
    if (process.argv.includes("--list")) {
      for (const r of open) console.log(`        ${r.id.padEnd(14)} §${r.section}`);
    }
  }
}

if (failures.size > 0) {
  for (const f of failures) console.error(f);
  process.exit(1);
}
if (!process.argv.includes("--coverage")) {
  console.log(
    `spec guard: ${requirements.length} requirements, ${markdown.length} markdown files, all checks pass`,
  );
}
